name: Publish Cloudflare Worker

on:
  release:
    types: [published]

jobs:
  publish-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v23.8.0'

      - name: Get latest tag version
        id: tag_version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
      
      - name: Update WORKER_VERSION in wrangler.toml
        run: |
          VERSION=${{ steps.tag_version.outputs.version }}
          echo "Updating WORKER_VERSION to $VERSION"
          sed -i "s/WORKER_VERSION = \".*\"/WORKER_VERSION = \"$VERSION\"/" wrangler.toml
          cat wrangler.toml

      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Publish Worker
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
